name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8
        run: flake8 .

      - name: Make wait-for-it.sh executable
        run: chmod +x ./wait-for-it.sh

      - name: Start API and wait for it
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          ./wait-for-it.sh localhost:8000 --timeout=60 --strict -- echo "API is up"

      - name: Run tests
        run: pytest

