name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        pip install -r requirements.txt

    - name: Build and run Docker container
      run: |
        docker-compose up -d --build

    - name: Wait for API to be up
      run: ./wait-for-it.sh localhost:8000 --timeout=60 --strict -- echo "API is up"

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -v
